### ISSUE TITLE
大神能否贡献下react + redux 的实例

### ISSUE THREAD

**Issue by yhhwpp** [logzh/resource#1]
看到https://segmentfault.com/a/1190000004660725 知乎 的文章总结的不错。大神你们的项目是否开源了。 小

**Comment by logzh** [comment]
@yhhwpp 周末上一个模板，你到时候再看看

**Comment by yhhwpp** [comment]
@logzh 感谢大神。周末我等着哦

**Comment by logzh** [comment]
@yhhwpp https://github.com/logzh/react-redux-webpack-boilerplate

**Comment by yhhwpp** [comment]
@logzh 感谢
